# REVISÃO DA LITERATURA

Ao longo dos anos, prevaleceu a visão de uma empresa que trabalha não isolada, mas em conjunto com outras empresas (Chae et al., 2014). Assim, estruturas da cadeia de suprimentos cada vez mais complexas em ambientes dinâmicos exigem capacidade de resposta e produtividade, nas quais os recursos existentes do sistema são empregados da maneira mais eficiente possível (Ehm et al., 2015; Frazzon, Albrecht, et al., 2018). A indústria 4.0 e sua ampla gama de conceitos e tecnologias (Lasi et al., 2014) podem contribuir para a materialização da produtividade e da capacidade de resposta. No entanto, conectar muitas organizações, operações e clientes leva a um cenário de alta incerteza de diferentes fontes (Peidro et al., 2009). No entanto, isso deve ser considerado nas questões de planejamento e controle, a fim de obter políticas e planos robustos.


Para lidar com esse comportamento, a otimização baseada em simulação é uma abordagem que possui recursos para lidar eficientemente com um cenário estendido, levando em consideração a dinâmica dos sistemas, levando a soluções quase ótimas em um tempo viável (Liotta et al., 2016). Métodos baseados em simulação podem ser usados para desenvolver e avaliar sistemas complexos. Aspectos como configuração física ou regras operacionais de um sistema podem ser considerados. Suas aplicações cresceram em diversas áreas, auxiliando os gerentes no processo de tomada de decisão e permitindo uma melhor compreensão dos processos em sistemas complexos (Sakurada e Miyake, 2009). Essas premissas são expressas em relações matemáticas, lógicas e simbólicas entre as entidades ou objetos de interesse do sistema. Dessa forma, as possíveis alterações do sistema podem primeiro ser simuladas para prever seu impacto no desempenho do sistema. Além disso, a simulação também permite ao tomador de decisão avaliar várias políticas de controle (Pirard et al., 2011). Numerosas réplicas das simulações podem ser realizadas para avaliar a robustez do projeto implementado. Infelizmente, a simulação não garante um design ideal. No entanto, a desvantagem apresentada pode ser equilibrada com a integração de outras ferramentas, como a modelagem matemática.


A combinação de modelos de simulação e programação matemática em um esquema iterativo, visa avaliar os efeitos das decisões no desempenho de um sistema de manufatura. Assim, trabalhos nesse sentido concentram-se na integração de diferentes metodologias de modelagem, a fim de combinar as vantagens oferecidas por cada uma delas na solução de problemas complexos. Os modelos analíticos buscam soluções que avaliam os valores ideais das variáveis de decisão. No entanto, as soluções fornecidas são geralmente limitadas em seus campos de aplicação devido a premissas restritivas predeterminadas. Os modelos de simulação, por sua vez, são mais capazes de capturar o comportamento real do sistema, mas não são adequados para resolver problemas de otimização. A integração de modelos analíticos e de simulação, também chamados de modelos híbridos, leva a representar uma opção promissora para melhores resultados (Lin e Chen, 2015). Assim, os modelos híbridos buscam combinar as vantagens e evitar as desvantagens de ambas as ferramentas (Peidro et al., 2009).

